[package]
name = "routerify-websocket"
version = "0.1.0"
description = "An websocket extension for Routerify."
homepage = "https://github.com/routerify/routerify-websocket"
repository = "https://github.com/routerify/routerify-websocket"
keywords = ["routerify", "hyper-rs", "hyper", "websocket", "ws"]
categories = ["asynchronous","web-programming","web-programming::http-server"]
authors = ["Rousan Ali <hello@rousan.io>"]
readme = "README.md"
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
features = ["all"]

[features]
default = []
all = []

[dependencies]
log = "0.4"
derive_more = "0.99"
routerify = "1.1"
hyper = "0.13"
tokio-tungstenite = { version = "0.10", default-features = false, optional = true }
headers = { version = "0.3", optional = true }
futures = { version = "0.3", default-features = false, optional = true }
tokio = { version = "0.2", features = ["rt-core"],  optional = true}

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }